baseURL: "https://Maxllevy.github.io/wildland-fire-library/"
title: "Wildland Fire Data Library"
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
languageCode: "en-us"

taxonomies:
  tag: "tags"
  category: "categories"
  landowner_category: "landowner_categories"
  student_category: "student_categories"
  researcher_category: "researcher_categories"

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Tags
      url: /tags/
      weight: 2
    - name: "Suggest a Resource"
      url: "https://app.formbricks.com/s/cm5fpim0i0000jn03zar52rrc"
      weight: 3
    - name: "Help"
      url: "/help/"
      weight: 4

params:
  hideList: true
  homeInfoParams:
    enabled: true

  # Disable schema generation
  schema:
    disable: true

  # Your existing terms and categories
  terms:
    smoke_preparation: "Smoke Preparation"
    landowner/fire_preparedness/stay_informed: "Stay Informed"
    landowner/fire_preparedness/current_fire_information: "Current Fire Information"
    available_grants: "Available Grants"
    grant_writing_tips: "Grant-Writing Tips"
    building_and_maintaining: "Building and Maintaining"
    climate: "Climate Data and Research"
    current_strategies: "Current Strategies"
    research_databases: "Research Databases"
    financial_assistance: "Financial Assistance"
    mentorships: "Mentorships"
    jobs: "Job Boards"
  landowner:
    fire_preparedness:
      - "Escape Plans"
      - "Stay Informed"
      - "Current Fire Information"
      - "Smoke Preparation"
    property_management:
      - "Building and Maintaining"
    grants:
      - "Available Grants"
      - "Grant-Writing Tips"
  student:
    academic_assistance:
      - "Mentorships"
      - "Financial Assistance"
    career_assistance:
      - "Jobs"
  researcher:
    - "Climate"
    - "Research Databases"
    - "Current Strategies"