name: Grammar Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vale:
    name: Vale grammar/style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@v2
        with:
          files: content/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}