name: Hugo Site Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: Validate YAML Front Matter
        run: |
          find content -name "*.md" -type f -exec sh -c '
            echo "Checking YAML in {}"
            front_matter=$(sed -n "/^---$/,/^---$/p" "{}")
            if ! echo "$front_matter" | yamllint -; then
              echo "YAML validation failed for {}"
              exit 1
            fi
          ' \;

      - name: Build Site
        run: |
          if ! hugo --minify; then
            echo "Hugo build failed"
            exit 1
          fi

          if [ ! -d "public" ]; then
            echo "Error: public directory was not created"
            exit 1
          fi

      - name: Install html-proofer
        run: sudo gem install html-proofer

      - name: Run html-proofer
        if: success()
        run: |
          if [ ! -d "public" ]; then
            echo "Error: public directory not found"
            exit 1
          fi
          htmlproofer ./public \
            --checks 'Links,Images,Scripts,Favicon,Html' \
            --disable-external \
            --ignore-urls "/^#$/" \
            --ignore-missing-alt

      - name: Check for broken internal links
        run: |
          set -e  # Exit immediately if any command fails
          find public -name "*.html" -type f -exec \
            grep -l "href=\"[^http]" {} \; | while read file; do
            echo "Checking $file"
            grep -o 'href="[^"]*"' "$file" | grep -v "^href=\"http" | \
            while read link; do
              target=$(echo $link | sed 's/href="\(.*\)"/\1/')
              if [[ $target != "#"* && ! -f "public/$target" && ! -f "public/$target/index.html" ]]; then
                echo "Broken link in $file: $target"
                exit 1
              fi
            done || exit 1
          done || exit 1