name: Hugo Site Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: Validate YAML Front Matter
        run: |
          find content -name "*.md" -type f -exec sh -c '
            echo "Checking YAML in {}"
            front_matter=$(sed -n "/^---$/,/^---$/p" "{}")
            if ! echo "$front_matter" | yamllint -; then
              echo "YAML validation failed for {}"
              exit 1
            fi
          ' \;

      - name: Validate Front Matter
        run: |
          find content -name "*.md" -type f -exec sh -c '
            echo "Checking front matter in {}"
            if ! hugo --quiet -e development --renderToMemory content/$(realpath --relative-to=content {}); then
              echo "Front matter validation failed for {}"
              exit 1
            fi
          ' \;

      - name: Build Site
        run: |
          # Enable verbose output for debugging
          HUGO_LOGFILE=hugo.log
          hugo --logFile $HUGO_LOGFILE --verbose --minify || {
            echo "Hugo build failed. Last 50 lines of log:"
            tail -n 50 $HUGO_LOGFILE
            exit 1
          }

      - name: Install html-proofer
        run: sudo gem install html-proofer

      - name: Run html-proofer
        run: |
          htmlproofer ./public \
            --check-html \
            --check-img-http \
            --check-links \
            --disable-external \
            --enforce-https \
            --ignore-urls "/^#$/" \
            --alt-ignore '/.*/' \
            --allow-hash-href

      - name: Install pa11y
        run: |
          npm install -g pa11y-ci

      - name: Run accessibility tests
        run: |
          echo '{"defaults": {"timeout": 10000}}' > .pa11yci
          pa11y-ci ./public/**/*.html

      - name: Check for broken internal links
        run: |
          set -e  # Exit immediately if any command fails
          find public -name "*.html" -type f -exec \
            grep -l "href=\"[^http]" {} \; | while read file; do
            echo "Checking $file"
            grep -o 'href="[^"]*"' "$file" | grep -v "^href=\"http" | \
            while read link; do
              target=$(echo $link | sed 's/href="\(.*\)"/\1/')
              if [[ $target != "#"* && ! -f "public/$target" && ! -f "public/$target/index.html" ]]; then
                echo "Broken link in $file: $target"
                exit 1
              fi
            done || exit 1
          done || exit 1